In [2]:
import numpy as np

In [3]:
X_train = np.array([[2104, 5, 1, 45], [1416, 3, 2, 40], [852, 2, 1, 35]])
y_train = np.array([460, 232, 178])

In [5]:
X_train

array([[2104,    5,    1,   45],
       [1416,    3,    2,   40],
       [ 852,    2,    1,   35]])

In [6]:
y_train

array([460, 232, 178])

In [7]:
X_train.shape

(3, 4)

In [8]:
y_train.shape

(3,)

In [9]:
b_init = 785.1811367994083
w_init = np.array([ 0.39133535, 18.75376741, -53.36032453, -26.42131618])
print(f"w_init shape: {w_init.shape}, b_init type: {type(b_init)}")

w_init shape: (4,), b_init type: <class 'float'>


In [15]:
def predict(x,w,b):
    value = np.dot(x,w)+b
    return value

In [21]:
x_vec = X_train[0,:]

In [22]:
x_vec

array([2104,    5,    1,   45])

In [23]:
x_vec.shape

(4,)

In [24]:
pred = predict(x_vec,w_init,b_init)
pred

459.9999976194083

In [34]:
def compute_cost(x,y,w,b):
    m=x.shape[0]
    sum = 0
    for i in range(m):
        f_wb = np.dot(x[i],w)+b
        sum=sum+((f_wb-y[i])**2)
    sum=sum/(2*m)
    return sum

In [35]:
cost = compute_cost(X_train,y_train,w_init,b_init)

In [36]:
cost

1.5578904428966628e-12