In [1]:
import numpy as np

In [3]:
import time

In [7]:
np.zeros(4)

array([0., 0., 0., 0.])

In [8]:
np.zeros((4))

array([0., 0., 0., 0.])

In [9]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

### Time Difference between dot product using loop and using numpy -> numpy is faster

In [51]:
a = np.array([1,2,3,4,5,6])
b = np.array([6,5,4,3,2,1])

In [52]:
a

array([1, 2, 3, 4, 5, 6])

In [53]:
a.shape

(6,)

In [64]:
a=np.random.rand(1000000)
b=np.random.rand(1000000)
tic = time.time()
np.dot(a,b)
toc = time.time()
print(f"np.dot(a, b) =  {c:.4f}")
print(f"Vectorized version duration: {1000*(toc-tic):.4f} ms ")

np.dot(a, b) =  56.0000
Vectorized version duration: 2.6934 ms 


In [65]:
def dot_product(a,b):
    sum = 0
    for i in range(a.shape[0]):
        sum=sum+a[i]*b[i]
    return sum

In [66]:
time_st=time.time()
c = dot_product(a,b)
time_end=time.time()
print(f"dot_product(a, b) =  {c:.8f}")
print(f"loop version duration: {1000*(time_end-time_st):.8f} ms ")

dot_product(a, b) =  250099.70983709
loop version duration: 285.02964973 ms 


In [58]:
sum

56

In [70]:
np.arange(6).reshape(-1,2)

array([[0, 1],
       [2, 3],
       [4, 5]])